/**
 * Created by wingo on 16/2/6.
 */
var data2 =  [{
    id: "a",
    gridColor: "#b2c8d3",
    wipeColors: ["#345e86", "#fdc76d", "#f38eae"],
    menuColor1: "#37618b",
    menuColor2: "#f48eb0",
    arrowsColor1: "#37618b",
    arrowsColor2: "#f48eb0",
    mobileMenuColor1: "#fdc76d",
    mobileMenuColor2: "#fffaed",
    imageCenter: "0.5",
    underlineWidth: "0.27",
    contentColor: "#37618b",
    accentColor: "#fec870",
    title: "American Spirits",
    titleOffset: "0",
    subtitle: "37x Cartons",
    description: "With all the dust in the air, you don’t want to further tarnish your lungs with generic brand smokes."
}, {
    id: "b",
    gridColor: "#c95031",
    wipeColors: ["#f5b38c", "#65141b", "#fdc76d"],
    menuColor1: "#fffaeb",
    menuColor2: "#c95031",
    arrowsColor1: "#fffaeb",
    arrowsColor2: "#c95031",
    mobileMenuColor1: "#fdc76d",
    mobileMenuColor2: "#fffaed",
    imageCenter: "0.5",
    underlineWidth: "0.20",
    contentColor: "#c95031",
    accentColor: "#f5b38c",
    title: "Brunch",
    titleOffset: "-0.05",
    subtitle: "37x Cartons",
    description: "Earthquake be damned, brunch will find a way. Powdered eggs? Jerky Hash? Figure it out and stock up."
}, {
    id: "c",
    gridColor: "#00b3ad",
    wipeColors: ["#112c3f", "#00b3ad", "#ecb1c5"],
    menuColor1: "#fff0c7",
    menuColor2: "#ecb1c5",
    arrowsColor1: "#fff0c7",
    arrowsColor2: "#ecb1c5",
    mobileMenuColor1: "#ecb1c5",
    mobileMenuColor2: "#fff4d6",
    imageCenter: "0.5",
    underlineWidth: "0.21",
    contentColor: "#02b1ac",
    accentColor: "#112c3f",
    title: "Crochet Hook",
    titleOffset: "-0.03",
    subtitle: "37x Cartons",
    description: "Add a touch of whimsy to the wreckage by yarn bombing the shit out of it."
}, {
    id: "d",
    gridColor: "#b2c8d3",
    wipeColors: ["#b2c8d3", "#65141b", "#f38eae"],
    menuColor1: "#fff0c7",
    menuColor2: "#65141b",
    arrowsColor1: "#fff0c7",
    arrowsColor2: "#65141b",
    mobileMenuColor1: "#f38eae",
    mobileMenuColor2: "#fffaeb",
    imageCenter: "0.5",
    underlineWidth: "0.23",
    contentColor: "#65141b",
    accentColor: "#b2c8d3",
    title: "Dulse",
    titleOffset: "-0.05",
    subtitle: "37x Cartons",
    description: "Reasearchers at Oregon State developed this strain of seaweed that tastes like bacon. God exists. See: B"
}, {
    id: "e",
    gridColor: "#ff897b",
    menuColor1: "#fbfbfb",
    menuColor2: "#c6d09e",
    arrowsColor1: "#fbfbfb",
    arrowsColor2: "#c6d09e",
    mobileMenuColor1: "#c6d09e",
    mobileMenuColor2: "#fffaeb",
    imageCenter: "0.5",
    underlineWidth: "0.16",
    contentColor: "#ab422f",
    accentColor: "#c6d09e",
    title: "Elements of Style",
    titleOffset: "-0.06",
    subtitle: "37x Cartons",
    description: "Now that you have time to work on your writing, you'll want to get the grammar right in your Fight Club x Ramona Quimby crossover fic."
}, {
    id: "f",
    gridColor: "#154142",
    wipeColors: ["#154142", "#ab422f", "#fff0c7"],
    menuColor1: "#8db1b1",
    menuColor2: "#ac4232",
    arrowsColor1: "#8db1b1",
    arrowsColor2: "#ac4232",
    mobileMenuColor1: "#8db1b1",
    mobileMenuColor2: "#fef2c9",
    imageCenter: "0.5",
    underlineWidth: "0.15",
    contentColor: "#154142",
    accentColor: "#8db1b1",
    title: "French Press",
    titleOffset: "-0.06",
    description: "Because instant coffee isn't going to cut it. What are we animals?"
}, {
    id: "g",
    gridColor: "#959a9e",
    menuColor1: "#d3d5d7",
    menuColor2: "#221e1f",
    arrowsColor1: "#d3d5d7",
    arrowsColor2: "#221e1f",
    mobileMenuColor1: "#ff897b",
    mobileMenuColor2: "#d3d5d7",
    imageCenter: "0.5",
    underlineWidth: "0.27",
    contentColor: "#5b5f63",
    accentColor: "#ff897b",
    title: "Glue gun",
    titleOffset: "-0.05",
    subtitle: "37x Cartons",
    description: "You can sell or barter your hand-crafted rubble art at the Saturday Market."
}, {
    id: "h",
    gridColor: "#6d8746",
    wipeColors: ["#6d8746", "#6b3922", "#c95031"],
    menuColor1: "#c6d09e",
    menuColor2: "#6b3922",
    arrowsColor1: "#c6d09e",
    arrowsColor2: "#6b3922",
    mobileMenuColor1: "#c95031",
    mobileMenuColor2: "#fffaeb",
    imageCenter: "0.5",
    underlineWidth: "0.24",
    contentColor: "#6b3922",
    accentColor: "#c6d09e",
    title: "Hops",
    titleOffset: "-0.05",
    subtitle: "37x Cartons",
    description: "Did you get through your microbrew stash a little too fast? Brew your own, then see if your friends can guess the IBU!"
}, {
    id: "i",
    gridColor: "#887942",
    wipeColors: ["#887942", "#fdc76d", "#ab4230"],
    menuColor1: "#fffaeb",
    menuColor2: "#f38eae",
    arrowsColor1: "#fffaeb",
    arrowsColor2: "#f38eae",
    mobileMenuColor1: "#fec870",
    mobileMenuColor2: "#fffaeb",
    imageCenter: "0.5",
    underlineWidth: "0.07",
    contentColor: "#887942",
    accentColor: "#fdc76d",
    title: "Innertubes",
    titleOffset: "-0.06",
    subtitle: "37x Cartons",
    description: "You'll have the last laugh when you unicycle past your enemies in the nude."
}, {
    id: "j",
    gridColor: "#fdc76d",
    wipeColors: ["#fdc76d", "#8495af", "#112c3f"],
    menuColor1: "#fff0c7",
    menuColor2: "#8495af",
    arrowsColor1: "#fff0c7",
    arrowsColor2: "#8495af",
    mobileMenuColor1: "#112c3f",
    mobileMenuColor2: "#b2c8d3",
    imageCenter: "0.5",
    underlineWidth: "0.15",
    contentColor: "#112c3f",
    accentColor: "#fdc76d",
    title: "Jorts",
    titleOffset: "0.03",
    subtitle: "37x Cartons",
    description: "Eventually everyone’s jeans will get so tattered that they’ll cut them into jorts, but you’ll have done it before it was cool."
}, {
    id: "k",
    gridColor: "#112c3f",
    wipeColors: ["#112c3f", "#b2c8d3", "#6d8746"],
    menuColor1: "#b2c8d3",
    menuColor2: "#6d8746",
    arrowsColor1: "#b2c8d3",
    arrowsColor2: "#6d8746",
    mobileMenuColor1: "#6d8746",
    mobileMenuColor2: "#b2c8d3",
    imageCenter: "0.5",
    underlineWidth: "0.24",
    contentColor: "#345e86",
    accentColor: "#b2c8d3",
    title: "Kale Chips",
    titleOffset: "-0.06",
    subtitle: "37x Cartons",
    description: "These will give you your daily dose of superfood while you wait to harvest the fresh kale. It's also hilarious to eat crunchy food while you cry."
}, {
    id: "l",
    gridColor: "#65141b",
    menuColor1: "#ffd6bc",
    menuColor2: "#00b3ad",
    arrowsColor1: "#ffd6bc",
    arrowsColor2: "#00b3ad",
    mobileMenuColor1: "#00b3ad",
    mobileMenuColor2: "#fffaeb",
    imageCenter: "0.5",
    underlineWidth: "0.15",
    contentColor: "#ab422f",
    accentColor: "#f1955f",
    title: "Libations",
    titleOffset: "-0.06",
    subtitle: "37x Cartons",
    description: "In the old days, they did a shot before having a limb sawed off. You'll dull the pain with a sazerac."
}, {
    id: "m",
    gridColor: "#c95031",
    wipeColors: ["#6b3922", "#c95031", "#f2d1cc"],
    menuColor1: "#f3d0cc",
    menuColor2: "#c95031",
    arrowsColor1: "#f3d0cc",
    arrowsColor2: "#c95031",
    mobileMenuColor1: "#c95031",
    mobileMenuColor2: "#f3d0cc",
    imageCenter: "0.5",
    underlineWidth: "0.33",
    contentColor: "#6b3922",
    accentColor: "#f3d0cc",
    title: "Mustache Wax",
    titleOffset: "-0.02",
    subtitle: "37x Cartons",
    description: "Are you a dapper lumbersexual? Keep it up! Just also learn some actual outdoors skills."
}, {
    id: "n",
    gridColor: "#8db1b1",
    wipeColors: ["#154142", "#6d8746", "#c95031"],
    menuColor1: "#dfe8e8",
    menuColor2: "#c95031",
    arrowsColor1: "#dfe8e8",
    arrowsColor2: "#c95031",
    mobileMenuColor1: "#6d8746",
    mobileMenuColor2: "#dfe8e8",
    imageCenter: "0.5",
    underlineWidth: "0.27",
    contentColor: "#154142",
    accentColor: "#dfe8e8",
    title: "Nugs",
    titleOffset: "-0.05",
    subtitle: "37x Cartons",
    description: "It could be medicinal, it could be recreational, and it could also be the new currency."
}, {
    id: "o",
    gridColor: "#00b3ad",
    wipeColors: ["#8db1b1", "#00b3ad", "#eae7be"],
    menuColor1: "#eae7be",
    menuColor2: "#ecb1c5",
    arrowsColor1: "#eae7be",
    arrowsColor2: "#ecb1c5",
    mobileMenuColor1: "#122d40",
    mobileMenuColor2: "#eae7be",
    imageCenter: "0.5",
    underlineWidth: "0.28",
    contentColor: "#00b3ad",
    accentColor: "#eae7be",
    title: "Odor Control",
    titleOffset: "-0.05",
    subtitle: "37x Cartons",
    description: "Showers will be scarce and that crystal you've been rubbing on your pits isn't going to cut it anymore. (Not that it cut it in the first place.) See: P"
}, {
    id: "p",
    gridColor: "#c6d09e",
    menuColor1: "#eae7be",
    menuColor2: "#b7a0ba",
    arrowsColor1: "#eae7be",
    arrowsColor2: "#b7a0ba",
    mobileMenuColor1: "#b7a0ba",
    mobileMenuColor2: "#fffaeb",
    imageCenter: "0.5",
    underlineWidth: "0.19",
    contentColor: "#6b3922",
    accentColor: "#b7a0ba",
    title: "Patchouli",
    titleOffset: "-0.05",
    subtitle: "37x Cartons",
    description: "A must-have in your personal apothecary. Not only is the scent calming, but it will help you put out the vibe at your drum circle."
}, {
    id: "q",
    gridColor: "#00b3ad",
    wipeColors: ["#00b3ad", "#fdc76d", "#ff897b"],
    menuColor1: "#fff0c7",
    menuColor2: "#ff897b",
    arrowsColor1: "#fff0c7",
    arrowsColor2: "#ff897b",
    mobileMenuColor1: "#ff897b",
    mobileMenuColor2: "#fff0c7",
    imageCenter: "0.5",
    underlineWidth: "0.30",
    contentColor: "#00b3ad",
    accentColor: "#fdc76d",
    title: "Quinoa",
    titleOffset: "-0.05",
    subtitle: "37x Cartons",
    description: "You weren't thinking of stocking rice, were you? Your world may be falling to pieces, but that's no reason to eat empty carbs."
}, {
    id: "r",
    gridColor: "#c95031",
    wipeColors: ["#b2c8d3", "#fdc76d", "#345e86"],
    menuColor1: "#fff0c7",
    menuColor2: "#345e86",
    arrowsColor1: "#fff0c7",
    arrowsColor2: "#345e86",
    mobileMenuColor1: "#345e86",
    mobileMenuColor2: "#fff0c7",
    imageCenter: "0.5",
    underlineWidth: "0.22",
    contentColor: "#345e86",
    accentColor: "#b2c8d3",
    title: "Russian Novels",
    titleOffset: "-0.06",
    subtitle: "37x Cartons",
    description: "After your friends die in the quake you’ll want to know why this is all tragically beautiful."
}, {
    id: "s",
    gridColor: "#6b3922",
    wipeColors: ["#6b3922", "#f5b591", "#6d8746"],
    menuColor1: "#6b3922",
    menuColor2: "#fff7d8",
    arrowsColor1: "#6b3922",
    arrowsColor2: "#fff7d8",
    mobileMenuColor1: "#6d8746",
    mobileMenuColor2: "#fff7d8",
    imageCenter: "0.5",
    underlineWidth: "0.19",
    contentColor: "#6b3922",
    accentColor: "#f5b38c",
    title: "Seed Bombs",
    titleOffset: "-0.03",
    subtitle: "37x Cartons",
    description: "Everything you need to make pico de gallo - but you throw it!"
}, {
    id: "t",
    gridColor: "#221e1f",
    wipeColors: ["#00b3ad", "#eae7be", "#84898d"],
    menuColor1: "#eae7be",
    menuColor2: "#595e61",
    arrowsColor1: "#eae7be",
    arrowsColor2: "#595e61",
    mobileMenuColor1: "#5b6063",
    mobileMenuColor2: "#eae7be",
    imageCenter: "0.5",
    underlineWidth: "0.19",
    contentColor: "#5b6063",
    accentColor: "#eae7be",
    title: "Typewriter",
    titleOffset: "0",
    subtitle: "37x Cartons",
    description: "To keep your blog going. Do these things come in futura?"
}, {
    id: "u",
    gridColor: "#f38eae",
    wipeColors: ["#ecb1c5", "#00b3ad", "#fff4d6"],
    menuColor1: "#fff7d8",
    menuColor2: "#00b3ad",
    arrowsColor1: "#fff7d8",
    arrowsColor2: "#00b3ad",
    mobileMenuColor1: "#00b3ad",
    mobileMenuColor2: "#fff7d8",
    imageCenter: "0.5",
    underlineWidth: "0.24",
    contentColor: "#221e1f",
    accentColor: "#ecb1c5",
    title: "Ukelele",
    titleOffset: "-0.05",
    subtitle: "37x Cartons",
    description: "Remember when no one came to your open mic performance? Their calendars are clear now."
}, {
    id: "v",
    gridColor: "#ab422f",
    menuColor1: "#fff0c7",
    menuColor2: "#ab422f",
    arrowsColor1: "#fff0c7",
    arrowsColor2: "#ab422f",
    mobileMenuColor1: "#ab422f",
    mobileMenuColor2: "#fff0c7",
    imageCenter: "0.5",
    underlineWidth: "0.26",
    contentColor: "#345e86",
    accentColor: "#8295af",
    title: "Victrola",
    titleOffset: "-0.02",
    subtitle: "37x Cartons",
    description: "DJs can still crank out sweet tunes and tone their arms at the same time."
}, {
    id: "w",
    gridColor: "#221e1f",
    wipeColors: ["#221e1f", "#b7a0ba", "#fff4d6"],
    menuColor1: "#d9be21",
    menuColor2: "#b7a0ba",
    arrowsColor1: "#d9be21",
    arrowsColor2: "#b7a0ba",
    mobileMenuColor1: "#d9be21",
    mobileMenuColor2: "#814e57",
    imageCenter: "0.5",
    underlineWidth: "0.37",
    contentColor: "#221e1f",
    accentColor: "#b7a0ba",
    title: "Wiccan spellbook",
    titleOffset: "-0.04",
    subtitle: "37x Cartons",
    description: "It will behoove you to find favor with the goddess. May she bless your fleece with many zippered pockets."
}, {
    id: "x",
    gridColor: "#ecb1c5",
    wipeColors: ["#ecb1c5", "#fff0c7", "#221e1f"],
    menuColor1: "#fff0c7",
    menuColor2: "#221e1f",
    arrowsColor1: "#fff0c7",
    arrowsColor2: "#221e1f",
    mobileMenuColor1: "#b2c8d3",
    mobileMenuColor2: "#fff0c7",
    imageCenter: "0.5",
    underlineWidth: "0.28",
    contentColor: "#221e1f",
    accentColor: "#ecb1c5",
    title: "Xanax",
    titleOffset: "0.02",
    subtitle: "37x Cartons",
    description: "Stressful times call for pharmaceuticals. If you're a millennial, you'll want to stockpile your Adderall. "
}, {
    id: "y",
    gridColor: "#b2c8d3",
    wipeColors: ["#b2c8d3", "#d78936", "#345e86"],
    menuColor1: "#345e86",
    menuColor2: "#d78936",
    arrowsColor1: "#345e86",
    arrowsColor2: "#d78936",
    mobileMenuColor1: "#112c3f",
    mobileMenuColor2: "#d78936",
    imageCenter: "0.5",
    underlineWidth: "0.26",
    contentColor: "#345e86",
    accentColor: "#b2c8d3",
    title: "Yoga pants",
    titleOffset: "0",
    subtitle: "37x Cartons",
    description: "Appropriate for exercise or just running errands around the FEMA tents with your $600 jogging stroller."
}, {
    id: "z",
    gridColor: "#8495af",
    menuColor1: "#fff0c7",
    menuColor2: "#c64f30",
    arrowsColor1: "#fff0c7",
    arrowsColor2: "#c64f30",
    mobileMenuColor1: "#f1955f",
    mobileMenuColor2: "#fff0c7",
    imageCenter: "0.5",
    underlineWidth: "0.23",
    contentColor: "#c64f30",
    accentColor: "#f1955f",
    title: "Zepplin",
    titleOffset: "0",
    subtitle: "37x Cartons",
    description: "If you can't cut it in the new Portland landscape, you can fly away to Austin. And what could be a weirder way to leave?"
}];